# Site settings
title: My Game List
SEOTitle: 永 無 止 境
header-img: img/home-bg.jpg  #记住这个文件名称的路径
email:  #我删了
description: "Welocome stranger! "
keyword: "这里就是我的游玩清单了"
url: "Player3A7"         # your host, for absolute URL
baseurl: ""     # for example, '/blog' if your blog hosted on 'host/blog'


# Publish posts or collection documents with a future date.
future: true  #我更改过，原本为true

# SNS settings

# RSS: false
# weibo_username: huxpro
# zhihu_username: huxpro
# github_username: huxpro
# twitter_username: huxpro
# facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: 3A7    #原为hux

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "多玩才能有新点子 <br> 持续通关中"
sidebar-avatar: https://github.com/Huxpro.png  # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags   这玩意就是脑袋上的一些TAG，建议先修改，实在不行就屏蔽
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends   建议直接全部屏蔽
# friends:
#   [
#     { title: "乱序（Midare）", href: "http://mida.re/" },
#     { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
#     { title: "Kun Qian", href: "http://kunq.me" },
#     { title: "Sherry Woo", href: "https://sherrywoo.me/" },
#     { title: "SmdCn", href: "http://blog.smdcn.net" },
#     { title: "JiyinYiyong", href: "http://tiye.me/" },
#     { title: "DHong Say", href: "http://dhong.co" },
#     { title: "尹峰以为", href: "http://ingf.github.io/" },
#   ]
